// Generated by CIRCT firtool-1.138.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TinySketch(	// src/main/scala/TinySketch.scala:53:7
  input        clock,	// src/main/scala/TinySketch.scala:53:7
               reset,	// src/main/scala/TinySketch.scala:53:7
  input  [7:0] io_value,	// src/main/scala/TinySketch.scala:55:14
  input        io_update_valid,	// src/main/scala/TinySketch.scala:55:14
               io_query_valid,	// src/main/scala/TinySketch.scala:55:14
  output [7:0] io_query_result	// src/main/scala/TinySketch.scala:55:14
);

  reg  [7:0]       tables_0_0;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_1;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_2;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_3;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_4;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_5;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_6;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_7;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_8;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_9;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_10;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_11;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_12;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_13;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_14;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_15;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_16;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_17;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_18;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_19;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_20;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_21;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_22;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_23;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_24;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_25;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_26;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_27;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_28;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_29;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_30;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_31;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_32;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_33;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_34;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_35;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_36;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_37;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_38;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_39;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_40;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_41;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_42;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_43;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_44;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_45;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_46;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_47;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_48;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_49;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_50;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_51;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_52;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_53;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_54;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_55;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_56;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_57;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_58;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_59;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_60;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_61;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_62;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_0_63;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_0;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_1;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_2;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_3;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_4;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_5;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_6;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_7;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_8;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_9;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_10;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_11;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_12;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_13;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_14;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_15;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_16;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_17;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_18;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_19;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_20;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_21;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_22;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_23;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_24;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_25;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_26;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_27;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_28;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_29;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_30;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_31;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_32;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_33;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_34;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_35;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_36;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_37;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_38;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_39;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_40;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_41;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_42;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_43;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_44;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_45;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_46;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_47;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_48;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_49;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_50;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_51;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_52;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_53;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_54;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_55;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_56;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_57;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_58;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_59;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_60;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_61;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_62;	// src/main/scala/TinySketch.scala:62:23
  reg  [7:0]       tables_1_63;	// src/main/scala/TinySketch.scala:62:23
  wire [5:0]       _GEN = io_value[5:0] ^ 6'h23;	// src/main/scala/TinySketch.scala:42:21, :55:14
  wire [63:0][7:0] _GEN_0 =
    {{tables_0_63},
     {tables_0_62},
     {tables_0_61},
     {tables_0_60},
     {tables_0_59},
     {tables_0_58},
     {tables_0_57},
     {tables_0_56},
     {tables_0_55},
     {tables_0_54},
     {tables_0_53},
     {tables_0_52},
     {tables_0_51},
     {tables_0_50},
     {tables_0_49},
     {tables_0_48},
     {tables_0_47},
     {tables_0_46},
     {tables_0_45},
     {tables_0_44},
     {tables_0_43},
     {tables_0_42},
     {tables_0_41},
     {tables_0_40},
     {tables_0_39},
     {tables_0_38},
     {tables_0_37},
     {tables_0_36},
     {tables_0_35},
     {tables_0_34},
     {tables_0_33},
     {tables_0_32},
     {tables_0_31},
     {tables_0_30},
     {tables_0_29},
     {tables_0_28},
     {tables_0_27},
     {tables_0_26},
     {tables_0_25},
     {tables_0_24},
     {tables_0_23},
     {tables_0_22},
     {tables_0_21},
     {tables_0_20},
     {tables_0_19},
     {tables_0_18},
     {tables_0_17},
     {tables_0_16},
     {tables_0_15},
     {tables_0_14},
     {tables_0_13},
     {tables_0_12},
     {tables_0_11},
     {tables_0_10},
     {tables_0_9},
     {tables_0_8},
     {tables_0_7},
     {tables_0_6},
     {tables_0_5},
     {tables_0_4},
     {tables_0_3},
     {tables_0_2},
     {tables_0_1},
     {tables_0_0}};	// src/main/scala/TinySketch.scala:62:23, :73:40
  wire [5:0]       _GEN_1 = io_value[5:0] ^ 6'h28;	// src/main/scala/TinySketch.scala:42:21, :55:14
  wire [63:0][7:0] _GEN_2 =
    {{tables_1_63},
     {tables_1_62},
     {tables_1_61},
     {tables_1_60},
     {tables_1_59},
     {tables_1_58},
     {tables_1_57},
     {tables_1_56},
     {tables_1_55},
     {tables_1_54},
     {tables_1_53},
     {tables_1_52},
     {tables_1_51},
     {tables_1_50},
     {tables_1_49},
     {tables_1_48},
     {tables_1_47},
     {tables_1_46},
     {tables_1_45},
     {tables_1_44},
     {tables_1_43},
     {tables_1_42},
     {tables_1_41},
     {tables_1_40},
     {tables_1_39},
     {tables_1_38},
     {tables_1_37},
     {tables_1_36},
     {tables_1_35},
     {tables_1_34},
     {tables_1_33},
     {tables_1_32},
     {tables_1_31},
     {tables_1_30},
     {tables_1_29},
     {tables_1_28},
     {tables_1_27},
     {tables_1_26},
     {tables_1_25},
     {tables_1_24},
     {tables_1_23},
     {tables_1_22},
     {tables_1_21},
     {tables_1_20},
     {tables_1_19},
     {tables_1_18},
     {tables_1_17},
     {tables_1_16},
     {tables_1_15},
     {tables_1_14},
     {tables_1_13},
     {tables_1_12},
     {tables_1_11},
     {tables_1_10},
     {tables_1_9},
     {tables_1_8},
     {tables_1_7},
     {tables_1_6},
     {tables_1_5},
     {tables_1_4},
     {tables_1_3},
     {tables_1_2},
     {tables_1_1},
     {tables_1_0}};	// src/main/scala/TinySketch.scala:62:23, :73:40
  wire [7:0]       _GEN_3 = _GEN_0[_GEN * 6'h19];	// src/main/scala/TinySketch.scala:42:21, :44:32, :45:32, :73:40, :82:27
  wire [7:0]       _GEN_4 = _GEN_2[_GEN_1 * 6'h19];	// src/main/scala/TinySketch.scala:42:21, :44:32, :45:32, :73:40, :82:27
  always @(posedge clock) begin	// src/main/scala/TinySketch.scala:53:7
    if (reset) begin	// src/main/scala/TinySketch.scala:53:7
      tables_0_0 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_1 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_2 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_3 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_4 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_5 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_6 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_7 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_8 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_9 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_10 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_11 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_12 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_13 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_14 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_15 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_16 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_17 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_18 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_19 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_20 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_21 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_22 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_23 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_24 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_25 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_26 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_27 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_28 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_29 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_30 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_31 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_32 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_33 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_34 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_35 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_36 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_37 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_38 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_39 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_40 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_41 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_42 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_43 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_44 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_45 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_46 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_47 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_48 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_49 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_50 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_51 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_52 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_53 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_54 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_55 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_56 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_57 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_58 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_59 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_60 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_61 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_62 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_0_63 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_0 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_1 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_2 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_3 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_4 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_5 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_6 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_7 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_8 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_9 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_10 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_11 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_12 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_13 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_14 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_15 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_16 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_17 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_18 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_19 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_20 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_21 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_22 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_23 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_24 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_25 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_26 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_27 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_28 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_29 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_30 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_31 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_32 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_33 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_34 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_35 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_36 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_37 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_38 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_39 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_40 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_41 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_42 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_43 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_44 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_45 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_46 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_47 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_48 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_49 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_50 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_51 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_52 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_53 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_54 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_55 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_56 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_57 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_58 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_59 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_60 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_61 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_62 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
      tables_1_63 <= 8'h0;	// src/main/scala/TinySketch.scala:62:23
    end
    else begin	// src/main/scala/TinySketch.scala:53:7
      automatic logic [5:0] _idx_T_6 = _GEN * 6'h19;	// src/main/scala/TinySketch.scala:42:21, :44:32, :45:32
      automatic logic [7:0] _tables_0_T_1;	// src/main/scala/TinySketch.scala:73:40
      automatic logic [5:0] _idx_T_17 = _GEN_1 * 6'h19;	// src/main/scala/TinySketch.scala:42:21, :44:32, :45:32
      automatic logic [7:0] _tables_1_T_1;	// src/main/scala/TinySketch.scala:73:40
      _tables_0_T_1 = _GEN_0[_idx_T_6] + 8'h1;	// src/main/scala/TinySketch.scala:44:32, :45:32, :73:40
      _tables_1_T_1 = _GEN_2[_idx_T_17] + 8'h1;	// src/main/scala/TinySketch.scala:44:32, :45:32, :73:40
      if (io_update_valid & _idx_T_6 == 6'h0)	// src/main/scala/TinySketch.scala:44:32, :45:32, :53:7, :62:23, :70:25, :73:22
        tables_0_0 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h1)	// src/main/scala/TinySketch.scala:44:32, :45:32, :53:7, :62:23, :70:25, :73:22
        tables_0_1 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h2)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_2 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h3)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_3 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h4)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_4 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h5)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_5 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h6)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_6 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h7)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_7 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h8)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_8 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h9)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_9 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'hA)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_10 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'hB)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_11 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'hC)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_12 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'hD)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_13 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'hE)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_14 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'hF)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_15 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h10)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_16 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h11)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_17 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h12)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_18 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h13)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_19 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h14)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_20 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h15)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_21 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h16)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_22 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h17)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_23 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h18)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_24 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h19)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_25 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h1A)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_26 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h1B)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_27 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h1C)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_28 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h1D)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_29 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h1E)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_30 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h1F)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_31 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h20)	// src/main/scala/TinySketch.scala:44:32, :45:32, :53:7, :62:23, :70:25, :73:22
        tables_0_32 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h21)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_33 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h22)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_34 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h23)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_35 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h24)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_36 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h25)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_37 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h26)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_38 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h27)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_39 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h28)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_40 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h29)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_41 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h2A)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_42 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h2B)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_43 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h2C)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_44 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h2D)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_45 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h2E)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_46 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h2F)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_47 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h30)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_48 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h31)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_49 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h32)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_50 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h33)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_51 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h34)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_52 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h35)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_53 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h36)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_54 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h37)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_55 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h38)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_56 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h39)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_57 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h3A)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_58 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h3B)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_59 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h3C)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_60 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h3D)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_61 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_6 == 6'h3E)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_62 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & (&_idx_T_6))	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_0_63 <= _tables_0_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h0)	// src/main/scala/TinySketch.scala:44:32, :45:32, :53:7, :62:23, :70:25, :73:22
        tables_1_0 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h1)	// src/main/scala/TinySketch.scala:44:32, :45:32, :53:7, :62:23, :70:25, :73:22
        tables_1_1 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h2)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_2 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h3)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_3 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h4)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_4 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h5)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_5 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h6)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_6 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h7)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_7 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h8)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_8 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h9)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_9 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'hA)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_10 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'hB)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_11 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'hC)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_12 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'hD)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_13 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'hE)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_14 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'hF)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_15 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h10)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_16 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h11)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_17 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h12)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_18 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h13)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_19 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h14)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_20 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h15)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_21 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h16)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_22 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h17)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_23 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h18)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_24 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h19)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_25 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h1A)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_26 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h1B)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_27 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h1C)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_28 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h1D)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_29 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h1E)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_30 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h1F)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_31 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h20)	// src/main/scala/TinySketch.scala:44:32, :45:32, :53:7, :62:23, :70:25, :73:22
        tables_1_32 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h21)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_33 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h22)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_34 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h23)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_35 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h24)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_36 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h25)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_37 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h26)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_38 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h27)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_39 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h28)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_40 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h29)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_41 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h2A)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_42 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h2B)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_43 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h2C)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_44 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h2D)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_45 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h2E)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_46 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h2F)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_47 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h30)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_48 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h31)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_49 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h32)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_50 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h33)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_51 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h34)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_52 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h35)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_53 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h36)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_54 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h37)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_55 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h38)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_56 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h39)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_57 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h3A)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_58 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h3B)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_59 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h3C)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_60 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h3D)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_61 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & _idx_T_17 == 6'h3E)	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_62 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
      if (io_update_valid & (&_idx_T_17))	// src/main/scala/TinySketch.scala:44:32, :45:32, :62:23, :70:25, :73:22
        tables_1_63 <= _tables_1_T_1;	// src/main/scala/TinySketch.scala:62:23, :73:40
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/TinySketch.scala:53:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/TinySketch.scala:53:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/TinySketch.scala:53:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/TinySketch.scala:53:7
      automatic logic [31:0] _RANDOM[0:31];	// src/main/scala/TinySketch.scala:53:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/TinySketch.scala:53:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/TinySketch.scala:53:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/TinySketch.scala:53:7
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// src/main/scala/TinySketch.scala:53:7
        end	// src/main/scala/TinySketch.scala:53:7
        tables_0_0 = _RANDOM[5'h0][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_1 = _RANDOM[5'h0][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_2 = _RANDOM[5'h0][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_3 = _RANDOM[5'h0][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_4 = _RANDOM[5'h1][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_5 = _RANDOM[5'h1][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_6 = _RANDOM[5'h1][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_7 = _RANDOM[5'h1][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_8 = _RANDOM[5'h2][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_9 = _RANDOM[5'h2][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_10 = _RANDOM[5'h2][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_11 = _RANDOM[5'h2][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_12 = _RANDOM[5'h3][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_13 = _RANDOM[5'h3][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_14 = _RANDOM[5'h3][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_15 = _RANDOM[5'h3][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_16 = _RANDOM[5'h4][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_17 = _RANDOM[5'h4][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_18 = _RANDOM[5'h4][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_19 = _RANDOM[5'h4][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_20 = _RANDOM[5'h5][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_21 = _RANDOM[5'h5][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_22 = _RANDOM[5'h5][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_23 = _RANDOM[5'h5][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_24 = _RANDOM[5'h6][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_25 = _RANDOM[5'h6][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_26 = _RANDOM[5'h6][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_27 = _RANDOM[5'h6][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_28 = _RANDOM[5'h7][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_29 = _RANDOM[5'h7][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_30 = _RANDOM[5'h7][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_31 = _RANDOM[5'h7][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_32 = _RANDOM[5'h8][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_33 = _RANDOM[5'h8][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_34 = _RANDOM[5'h8][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_35 = _RANDOM[5'h8][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_36 = _RANDOM[5'h9][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_37 = _RANDOM[5'h9][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_38 = _RANDOM[5'h9][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_39 = _RANDOM[5'h9][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_40 = _RANDOM[5'hA][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_41 = _RANDOM[5'hA][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_42 = _RANDOM[5'hA][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_43 = _RANDOM[5'hA][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_44 = _RANDOM[5'hB][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_45 = _RANDOM[5'hB][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_46 = _RANDOM[5'hB][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_47 = _RANDOM[5'hB][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_48 = _RANDOM[5'hC][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_49 = _RANDOM[5'hC][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_50 = _RANDOM[5'hC][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_51 = _RANDOM[5'hC][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_52 = _RANDOM[5'hD][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_53 = _RANDOM[5'hD][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_54 = _RANDOM[5'hD][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_55 = _RANDOM[5'hD][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_56 = _RANDOM[5'hE][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_57 = _RANDOM[5'hE][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_58 = _RANDOM[5'hE][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_59 = _RANDOM[5'hE][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_60 = _RANDOM[5'hF][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_61 = _RANDOM[5'hF][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_62 = _RANDOM[5'hF][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_0_63 = _RANDOM[5'hF][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_0 = _RANDOM[5'h10][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_1 = _RANDOM[5'h10][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_2 = _RANDOM[5'h10][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_3 = _RANDOM[5'h10][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_4 = _RANDOM[5'h11][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_5 = _RANDOM[5'h11][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_6 = _RANDOM[5'h11][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_7 = _RANDOM[5'h11][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_8 = _RANDOM[5'h12][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_9 = _RANDOM[5'h12][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_10 = _RANDOM[5'h12][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_11 = _RANDOM[5'h12][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_12 = _RANDOM[5'h13][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_13 = _RANDOM[5'h13][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_14 = _RANDOM[5'h13][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_15 = _RANDOM[5'h13][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_16 = _RANDOM[5'h14][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_17 = _RANDOM[5'h14][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_18 = _RANDOM[5'h14][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_19 = _RANDOM[5'h14][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_20 = _RANDOM[5'h15][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_21 = _RANDOM[5'h15][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_22 = _RANDOM[5'h15][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_23 = _RANDOM[5'h15][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_24 = _RANDOM[5'h16][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_25 = _RANDOM[5'h16][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_26 = _RANDOM[5'h16][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_27 = _RANDOM[5'h16][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_28 = _RANDOM[5'h17][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_29 = _RANDOM[5'h17][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_30 = _RANDOM[5'h17][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_31 = _RANDOM[5'h17][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_32 = _RANDOM[5'h18][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_33 = _RANDOM[5'h18][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_34 = _RANDOM[5'h18][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_35 = _RANDOM[5'h18][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_36 = _RANDOM[5'h19][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_37 = _RANDOM[5'h19][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_38 = _RANDOM[5'h19][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_39 = _RANDOM[5'h19][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_40 = _RANDOM[5'h1A][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_41 = _RANDOM[5'h1A][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_42 = _RANDOM[5'h1A][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_43 = _RANDOM[5'h1A][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_44 = _RANDOM[5'h1B][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_45 = _RANDOM[5'h1B][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_46 = _RANDOM[5'h1B][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_47 = _RANDOM[5'h1B][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_48 = _RANDOM[5'h1C][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_49 = _RANDOM[5'h1C][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_50 = _RANDOM[5'h1C][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_51 = _RANDOM[5'h1C][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_52 = _RANDOM[5'h1D][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_53 = _RANDOM[5'h1D][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_54 = _RANDOM[5'h1D][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_55 = _RANDOM[5'h1D][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_56 = _RANDOM[5'h1E][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_57 = _RANDOM[5'h1E][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_58 = _RANDOM[5'h1E][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_59 = _RANDOM[5'h1E][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_60 = _RANDOM[5'h1F][7:0];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_61 = _RANDOM[5'h1F][15:8];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_62 = _RANDOM[5'h1F][23:16];	// src/main/scala/TinySketch.scala:53:7, :62:23
        tables_1_63 = _RANDOM[5'h1F][31:24];	// src/main/scala/TinySketch.scala:53:7, :62:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/TinySketch.scala:53:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/TinySketch.scala:53:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_query_result = io_query_valid ? (_GEN_3 < _GEN_4 ? _GEN_3 : _GEN_4) : 8'h0;	// src/main/scala/TinySketch.scala:53:7, :66:19, :77:24, :82:{19,27}, :84:21
endmodule

